Traceback (most recent call last):
  File "/home/fkaule/code/jupyterenvironment/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/fkaule/code/jupyterenvironment/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/fkaule/code/jupyterenvironment/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/fkaule/code/jupyterenvironment/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/fkaule/code/jupyterenvironment/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/fkaule/code/jupyterenvironment/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/fkaule/code/jupyterenvironment/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import pandas as pd

# Steifigkeiten
c1 = 0.55 # N/mm
c2 = 0.6 # N/mmh
c3 = 0.9 # N/mm
Federsteifigkeiten=[c1,c2,c3]

#Weg
Weglaenge = 10 # mm
Wegschritt = 2.5 # mm
Weg = np.arange(0, Weglaenge+Wegschritt, Wegschritt)

# Rauschen pro Messung 
M_mu, M_sigma = 0, 0.1 # Mittelwert und Standardabweichung f√ºr Rauschen Person 1

Anz_Messung=5

for j in range(len(Federsteifigkeiten)):

    Feder = j + 1 # Variable fuer Speichern der Textdatei
    Kraft = np.linspace(0, Weglaenge*Federsteifigkeiten[j], int(Weglaenge/Wegschritt)+1) # Kraftwerte bestimmen

    for i in range(Anz_Messung):

        Messung = i + 1              
        Noise = np.random.normal(M_mu, M_sigma, int(Weglaenge/Wegschritt)+1) # Rauschen des Kraftsensors
        
        # Daten erzeugen

        Kraftmessung = Kraft + Noise
        Kraftmessung[0] = 0 # ersten Wert Null setzen
        Kraftmessung = np.around(Kraftmessung, 1) # Werte runden
        Kraftmessung

        # in Dataframe speichern
        df=pd.DataFrame(Kraftmessung,Weg)
        df.reset_index(level=0, inplace=True)
        df.rename(columns = {"index":"Weg (mm)",
                            0:"Kraft (N)"},
                    inplace=True)

        # als csv exportieren
        filename_1='Feder_'
        filename_2='Messung_'
        
        filename=filename_1+str(Feder)+'-'+filename_2+str(Messung)+'.csv'
        df.to_csv (filename, index = False, header=True)

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-eb33828ebeb3>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mimport[0m [0mnumpy[0m [0;32mas[0m [0mnp[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;32mimport[0m [0mpandas[0m [0;32mas[0m [0mpd[0m[0;34m[0m[0;34m[0m[0m
[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0;31m# Steifigkeiten[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mc1[0m [0;34m=[0m [0;36m0.55[0m [0;31m# N/mm[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'numpy'
ModuleNotFoundError: No module named 'numpy'

