Traceback (most recent call last):
  File "/home/fkaule/code/jupyterenvironment/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/fkaule/code/jupyterenvironment/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/fkaule/code/jupyterenvironment/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/fkaule/code/jupyterenvironment/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/fkaule/code/jupyterenvironment/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/fkaule/code/jupyterenvironment/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/fkaule/code/jupyterenvironment/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd

# historische Daten einlesen
data_hist = pd.read_csv("produkt_klima_tag_19340101_20181231_02932.txt", sep=";")
data_hist = data_hist.loc[:,("MESS_DATUM"," RSK")]

# aktuelle Daten einlesen
data_aktuell = pd.read_csv("produkt_klima_tag_20190719_20210118_02932.txt", sep=";")
data_aktuell = data_aktuell.loc[:,("MESS_DATUM"," RSK")]

# Daten zusammenfuehren
df = pd.concat([data_hist, data_aktuell]).reset_index(drop=True)

# Spalte umbennnen
df.rename(columns={" RSK":"tgl. Niederschlagshoehe [mm]"}, inplace=True)

# Datumsformat einf√ºhren
df['Datum'] = pd.to_datetime(df['MESS_DATUM'],format='%Y%m%d')

# Tag/Monat/Jahr Spalte hinzufuegen
df["Jahr"] = pd.DatetimeIndex(df['Datum']).year
df["Monat"] = pd.DatetimeIndex(df['Datum']).month
df["Tag"] = pd.DatetimeIndex(df['Datum']).day

# Spalte MESS_DATUM entfernen
df = df.drop(["MESS_DATUM"],axis=1)

df
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-b7c39c02243d>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0;32mimport[0m [0mpandas[0m [0;32mas[0m [0mpd[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0;31m# historische Daten einlesen[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mdata_hist[0m [0;34m=[0m [0mpd[0m[0;34m.[0m[0mread_csv[0m[0;34m([0m[0;34m"produkt_klima_tag_19340101_20181231_02932.txt"[0m[0;34m,[0m [0msep[0m[0;34m=[0m[0;34m";"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mdata_hist[0m [0;34m=[0m [0mdata_hist[0m[0;34m.[0m[0mloc[0m[0;34m[[0m[0;34m:[0m[0;34m,[0m[0;34m([0m[0;34m"MESS_DATUM"[0m[0;34m,[0m[0;34m" RSK"[0m[0;34m)[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'pandas'
ModuleNotFoundError: No module named 'pandas'

